title = "Yannik Schmidt Freelance"
baseURL = 'https://potaris.de'

languageCode = 'en-us'
theme = "hugo-blog-awesome"
defaultContentLanguage = "de-de"
googleAnalytics = '' # G-MEASUREMENT_ID

enableEmoji = false
ignoreErrors = ["additional-script-loading-error"]
disqusShortname = ''

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2
		endLevel = 4
		ordered = false

############################## English language ################################
[Languages.en-gb]
  languageName = "English"
  languageCode = "en-gb"
  contentDir = "content/en"
  weight = 1

  [Languages.en-gb.menu]
  [[Languages.en-gb.menu.main]]
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[Languages.en-gb.menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[Languages.en-gb.menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[Languages.en-gb.params]
  sitename = "Yannik Schmidt"
  defaultColor = "dark"
  description = "Yannik Schmidt Freelancer Python, Linux, DevOps and Fullstack"
  mainSections = ['posts']
  toc = false
  tocOpen = false
  goToTop = true
  additionalScripts = ['js/custom.js', 'js/custom-2.js']
  dateFormat = ""
  rssFeedDescription = "summary"

[Languages.en-gb.params.author]
  avatar = "avatar.jpg"
  intro = "Yannik Schmidt"
  name = "Yannik Schmidt"
  description = "Freelancer focusing on Python, Linux, DevOps and Fullstack"

[Languages.en-gb.params.webmanifest]
  name = "sitename"
  short_name = "sitename"
  start_url = "/"
  theme_color = "#434648"
  background_color = "#fff"
  display = "standalone"

############################## German language ################################
[Languages.de-de]
  languageName = "German"
  languageCode = "de-de"
  contentDir = "content/de"
  weight = 1

  [Languages.de-de.menu]
  [[Languages.de-de.menu.main]]
    pageRef="/"
    name = 'Startseite'
    url = '/'
    weight = 10
  [[Languages.de-de.menu.main]]
    pageRef="posts"
    name = 'Themen Beiträge'
    url = '/posts/'
    weight = 20
  [[Languages.de-de.menu.main]]
    pageRef="about"
    name = 'Über mich'
    url = '/about/'
    weight = 30

[Languages.de-de.params]
  sitename = "Yannik Schmidt"
  defaultColor = "dark"
  description = "Yannik Schmidt Freelancer Python, Linux, DevOps (Fullstack)"
  mainSections = ['posts']
  toc = false
  tocOpen = false
  goToTop = true
  additionalScripts = ['js/custom.js', 'js/custom-2.js']
  dateFormat = ""
  rssFeedDescription = "summary"

[Languages.de-de.params.author]
  avatar = "avatar.jpg"
  intro = "Yannik Schmidt"
  name = "Yannik Schmidt"
  description = "Freelancer mit Schwerpunkt auf Python, Linux, DevOps und Fullstack"

[Languages.de-de.params.webmanifest]
  name = "sitename"
  short_name = "sitename"
  start_url = "/"
  theme_color = "#434648"
  background_color = "#fff"
  display = "standalone"

###################################################################

# Allow to override `browserconfig.xml` params (configuration for windows embeded browsers)
[params.browserconfig]
  TileColor = "#2d89ef" # default windows 10 blue tile color

[[params.socialIcons]]
name = "github"
url = "https://github.com/FAUSheppy"

[[params.socialIcons]]
name = "freelancermap"
url = "https://www.freelancermap.de/profil/yannik-schmidt"
