name: Container Build for atlantis-hub

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    environment:
        name: prod
    steps:
      - uses: actions/checkout@v3
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      -
        name: build and push potaris next-gen
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: "${{ secrets.REGISTRY }}/atlantishq/potaris-next-gen-web:latest"
